//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Expr.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IExprListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class ExprBaseListener : IExprListener {
	/// <summary>
	/// Enter a parse tree produced by the <c>DivPer</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDivPer([NotNull] ExprParser.DivPerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>DivPer</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDivPer([NotNull] ExprParser.DivPerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Potenza</c>
	/// labeled alternative in <see cref="ExprParser.operazione"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPotenza([NotNull] ExprParser.PotenzaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Potenza</c>
	/// labeled alternative in <see cref="ExprParser.operazione"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPotenza([NotNull] ExprParser.PotenzaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>negativiNumeri</c>
	/// labeled alternative in <see cref="ExprParser.numeri"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNegativiNumeri([NotNull] ExprParser.NegativiNumeriContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>negativiNumeri</c>
	/// labeled alternative in <see cref="ExprParser.numeri"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNegativiNumeri([NotNull] ExprParser.NegativiNumeriContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>SommaMenointerni</c>
	/// labeled alternative in <see cref="ExprParser.numeri"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSommaMenointerni([NotNull] ExprParser.SommaMenointerniContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>SommaMenointerni</c>
	/// labeled alternative in <see cref="ExprParser.numeri"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSommaMenointerni([NotNull] ExprParser.SommaMenointerniContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Number</c>
	/// labeled alternative in <see cref="ExprParser.numeri"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] ExprParser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Number</c>
	/// labeled alternative in <see cref="ExprParser.numeri"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] ExprParser.NumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Parent</c>
	/// labeled alternative in <see cref="ExprParser.numeri"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParent([NotNull] ExprParser.ParentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Parent</c>
	/// labeled alternative in <see cref="ExprParser.numeri"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParent([NotNull] ExprParser.ParentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>DivPerinterni</c>
	/// labeled alternative in <see cref="ExprParser.numeri"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDivPerinterni([NotNull] ExprParser.DivPerinterniContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>DivPerinterni</c>
	/// labeled alternative in <see cref="ExprParser.numeri"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDivPerinterni([NotNull] ExprParser.DivPerinterniContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
