//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Expr.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ExprParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IExprVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExprParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg([NotNull] ExprParser.ProgContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ParentesiEspressione</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParentesiEspressione([NotNull] ExprParser.ParentesiEspressioneContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MoltiplicazioneEspressione</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMoltiplicazioneEspressione([NotNull] ExprParser.MoltiplicazioneEspressioneContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CostanteEspressione</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCostanteEspressione([NotNull] ExprParser.CostanteEspressioneContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CasoEspressione</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCasoEspressione([NotNull] ExprParser.CasoEspressioneContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>RadiceEspressione</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRadiceEspressione([NotNull] ExprParser.RadiceEspressioneContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DerivataEspressione</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDerivataEspressione([NotNull] ExprParser.DerivataEspressioneContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DivisioneEspressione</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDivisioneEspressione([NotNull] ExprParser.DivisioneEspressioneContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PotenzaEspressione</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPotenzaEspressione([NotNull] ExprParser.PotenzaEspressioneContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SommaEspressione</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSommaEspressione([NotNull] ExprParser.SommaEspressioneContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SottrazioneEspressione</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSottrazioneEspressione([NotNull] ExprParser.SottrazioneEspressioneContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FunzioneEspressione</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunzioneEspressione([NotNull] ExprParser.FunzioneEspressioneContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NumeroEspressione</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumeroEspressione([NotNull] ExprParser.NumeroEspressioneContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Somma</c>
	/// labeled alternative in <see cref="ExprParser.ss"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSomma([NotNull] ExprParser.SommaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Divizione</c>
	/// labeled alternative in <see cref="ExprParser.ss"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDivizione([NotNull] ExprParser.DivizioneContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Number</c>
	/// labeled alternative in <see cref="ExprParser.ss"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber([NotNull] ExprParser.NumberContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Parens</c>
	/// labeled alternative in <see cref="ExprParser.ss"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParens([NotNull] ExprParser.ParensContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Sotrazione</c>
	/// labeled alternative in <see cref="ExprParser.ss"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSotrazione([NotNull] ExprParser.SotrazioneContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Moltipicazione</c>
	/// labeled alternative in <see cref="ExprParser.ss"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMoltipicazione([NotNull] ExprParser.MoltipicazioneContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Id</c>
	/// labeled alternative in <see cref="ExprParser.ss"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitId([NotNull] ExprParser.IdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExprParser.func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc([NotNull] ExprParser.FuncContext context);
}
